# Generated by Django 4.2.5 on 2023-10-01 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='semester',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Value must be between 1 and 8'), django.core.validators.MaxValueValidator(8, message='Value must be between 1 and 8')]),
        ),
    ]
