# Generated by Django 4.1.7 on 2023-10-29 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='questions_text_slug',
            field=models.TextField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='no_of_questions_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
