# Generated by Django 4.1.7 on 2023-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
