# Generated by Django 4.1.7 on 2023-10-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_questions_added_by_questions_questions_text_slug_and_more'),
        ('exam', '0002_questions_passage'),
    ]

    operations = [
    ]
