# Generated by Django 4.2.5 on 2023-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_regularuser_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='negetive_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='postive_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
