# Generated by Django 4.2.5 on 2023-10-02 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_negetive_marks_exam_postive_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value must be between 1 and 8'), django.core.validators.MaxValueValidator(8, message='Value must be between 1 and 8')]),
        ),
    ]
