# Generated by Django 4.1.7 on 2023-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_abstractotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userresponse',
            name='exam_name',
            field=models.CharField(default='test-1', max_length=150),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='qualify_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='time_taken',
            field=models.CharField(default='00:00:00', max_length=30),
        ),
    ]
