# Generated by Django 4.2.5 on 2023-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_department_exam_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('images_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionA_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionB_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionC_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='optionD_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='solution_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='questions/images/'),
        ),
    ]
