# Generated by Django 4.2.5 on 2023-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_sliderimage_alter_questions_optiona_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
    ]
