# Generated by Django 4.1.7 on 2023-11-22 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_regularuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(PRP|prp|LPRP|lprp)[0-9]{2}([A-Za-z]{2}|[0-9]{2})[0-9]{3}$')]),
        ),
    ]
